name: Create Beta Package

on:
  create:

jobs:
  is_beta:
    if: contains(github.ref, 'beta') == true
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        echo ${{ github.ref }}

    - name: Remove Changelog
      run: rm -f CHANGELOG.md

  mainline:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Mainline Package
      uses: BigWigsMods/packager@master
      with:
        args: -o

  bcc:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create BCC Package
      uses: BigWigsMods/packager@master
      with:
        args: -o -g bcc -m .pkgmeta-bcc

  classic:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Classic Package
      uses: BigWigsMods/packager@master
      with:
        args: -o -g classic -m .pkgmeta-classic
